export const ACTIVITY_ACTIONS = {
  CASE_CREATED: "CASE_CREATED",
  CASE_UPDATED: "CASE_UPDATED",
  CASE_DELETED: "CASE_DELETED",
  CASE_STATUS_CHANGED: "CASE_STATUS_CHANGED",

  STAGE_CREATED: "STAGE_CREATED",
  STAGE_UPDATED: "STAGE_UPDATED",
  STAGE_ASSIGNED: "STAGE_ASSIGNED",
  STAGE_COMPLETED: "STAGE_COMPLETED",

  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",

  NOTE_CREATED: "NOTE_CREATED",

  PAYMENT_REGISTERED: "PAYMENT_REGISTERED",

  USER_LOGIN: "USER_LOGIN",
} as const;

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[keyof typeof ACTIVITY_ACTIONS];

export const ACTIVITY_ACTION_VALUES = Object.values(ACTIVITY_ACTIONS) as [
  ActivityAction,
  ...ActivityAction[],
];
